export enum Statuses {
  INITIALIZING = 'INITIALIZING',
  FINALIZING = 'FINALIZING',
  SERVER_RUNNING = 'SERVER_RUNNING',
  SCHEDULER_RUNNING = 'SCHEDULER_RUNNING',
  SCHEDULER_ERROR = 'SCHEDULER_ERROR',
  SERVER_ERROR = 'SERVER_ERROR'
}
